### ISSUE TITLE
lmapM

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Foldl-Library#100]
I noticed `premapM`:

```haskell
premapM :: (a -> b) -> FoldM m b x -> FoldM a x
```

But how about a monad variant?

```haskell
lmapM :: (a -> m b) -> FoldM m b x -> FoldM m a x
```

**Comment by Gabriel439** [comment]
Yeah, that sounds good to me.  Could you submit a pull request?

**Comment by mitchellwrosen** [comment]
Sure. I also noticed there is a bit of an inconsistency in the naming scheme:

```haskell
-- M suffix distinguishes both the predicate and the fold type
prefilter :: (a -> Bool) -> Fold a b -> Fold a b
prefilterM :: (a -> m Bool) -> FoldM m a b -> FoldM m a b

-- M suffix only distinguishes fold type
premap :: (a -> b) -> Fold b x -> Fold a x
premapM (a -> b) -> FoldM m b x -> FoldM m b x
```

I wonder, should `premapM` just be made to take a monadic function instead?

**Comment by Gabriel439** [comment]
Yeah, I think for consistency we can just generalize `premapM` to take a monadic function
