### ISSUE TITLE
Question: alternate nub implementation

### ISSUE THREAD

**Issue by shineli1984** [Gabriel439/Haskell-Foldl-Library#103]
I was looking through the source code and stumbled on the implementation of `nub` function. While I understand the code, I couldn't help wonder if there is a specific reason that the step function is composing a function in the tuple? instead of accumulating the result list itself like the following? is there a difference here (in performance)?
```Haskell
nub :: Ord a => Fold a [a]
nub = Fold step (Pair Set.empty []) fin
  where
    step (Pair s r) a = if Set.member a s
      then Pair s r
      else Pair (Set.insert a s) (r ++ [a])
    fin (Pair _ r) = r
```

**Comment by Gabriel439** [comment]
@shineli1984: Yeah, there is a difference in performance.  The example you gave leads to quadratic time complexity since appending an element to the end of a linked list is O(N) time complexity for each append.

**Comment by shineli1984** [comment]
Ha... right. Thank you for the explaination.

**Comment by Gabriel439** [comment]
You're welcome! :)
