### ISSUE TITLE
instance Semigroupoid Fold

### ISSUE THREAD

**Issue by lspitzner** [Gabriel439/Haskell-Foldl-Library#110]
~~~~.hs
instance Semigroupoid Fold where
  o (Fold s1 b1 x1) (Fold s2 b2 x2) = Fold
    (\c a ->
      let c2' = s2 (snd c) a
          c1' = s1 (fst c) (x2 c2')
      in  (c1', c2')
    )
    (b1, b2)
    (x1 . fst)
~~~~

Seems to be a lawful instance although I have not done the proof. Also I cannot spot this functionality (`Fold b c -> Fold a b -> Fold a c`) in the existing exports.

**Comment by Gabriel439** [comment]
@lspitzner: Yeah, I'm reasonably certain that is a law-abiding instance.  I'd accept a pull request to add that
