### ISSUE TITLE
Now that we have Control.Scanl, how about Control.Scanr?

### ISSUE THREAD

**Issue by kccqzy** [Gabriel439/Haskell-Foldl-Library#117]
The new `Scanl` module is looking really great. However, by symmetry, one would want to have a `Scanr` module that basically does the same thing but (essentially) traverses the container in reverse. 

So the final `Scanl` and `Scanr` modules would be a generalization of base's [`mapAccumL`](http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Traversable.html#v:mapAccumL) and [`mapAccumR`](http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Traversable.html#v:mapAccumR).

In terms of implementation, the new `Scanr` module would be achieved through the use of the reverse state monad, just like `mapAccumR` in `base`. (This is the reverse state monad I'm talking about: <http://hackage.haskell.org/package/base-4.11.1.0/docs/src/Data.Functor.Utils.html#StateR>).

How do you like this idea? If this looks good, I can whip up a preliminary implementation soon.

**Comment by Gabriel439** [comment]
@kccqzy: I think this is a good idea, but I don't think this needs to be in a separate module.  The `Scan` type is not inherently directional and you can reuse the same type to process the container in reverse so I think this can be done by just adding extra utilities to the existing `Control.Scanl` module

**Comment by kccqzy** [comment]
Thanks! I can close this now.
