### ISSUE TITLE
Control.Scanl doesn't stream in constant space?

### ISSUE THREAD

**Issue by agrue** [Gabriel439/Haskell-Foldl-Library#137]
Hey there. Great library, I use and recommend it often.

Recently I tried using the somewhat new `Control.Scanl` module to express some list processing as a composition of `Scan`s. To my surprise, however, `Scan`s do not seem to stream in constant space, as illustrated by this example:

```haskell
module Main (main) where

import Control.Category
import Control.Scanl

import Prelude hiding (id)

main :: IO ()
main = print $ sum (scan id ([0..10000000] :: [Int]))
```

On my machine this runs with over 300 Mb max residency and only 17% productivity. (I can make a PR adding this as a test, if it makes it easier to reproduce)

I believe the problem lies in using the strict version of `StateT` instead of the lazy version in the internal representation of `Scan`. Instead of making the accumulator strict, this just sequences the computations strictly, so the output gets built up prematurely (I think?). Indeed, if I change the import in `Control.Scanl` from `Control.Monad.Trans.State.Strict` to `Control.Monad.Trans.State.Lazy` the above example streams in constant space (max residency of 44 kb and productivity of 90%+).

So I guess my questions are:

1. Have I identified a real issue or is there some other way I should be using the library to stream in constant space?

2. If I have identified a real issue, what's the fix? I think switching the `StateT` import from `Strict` to `Lazy` probably isn't the best solution, because it's both a breaking API change and doesn't even guarantee strict accumulation by itself (for that the user still needs to be careful to pass in computations that are strict in the new state, e.g. generated via `modify'`). I think ideally this would be enforced internally like it is for `Control.Foldl`.

Thoughts?

**Comment by Gabriel439** [comment]
@agrue: Yes, you've identified a real issue.  What's going on here is that the strictness prevents the `traverse` from returning any results until the entire computation has completed.

I'm totally fine making a breaking change if that's what's necessary to fix this.  I don't think it's an issue that users need to take care to use strict utilities like `modify'`.

**Comment by agrue** [comment]
Okay, thanks. I'll work on a patch. I think it can be done without breaking backwards compatibility, but it might make the implementation look a little strange. We'll see.

**Comment by agrue** [comment]
This issue is fixed. Thanks for merging... and sorry for sitting on this issue for over a year(!)

**Comment by Gabriel439** [comment]
@agrue: No worries, and thank you for the pull request 🙂
