### ISSUE TITLE
tail

### ISSUE THREAD

**Issue by jchia** [Gabriel439/Haskell-Foldl-Library#159]
Is there a special reason why there are `head`, `lastN` but no `tail`? Is it simply because the space complexity is not constant?

**Comment by Gabriel439** [comment]
Yeah, that is the reason: the space complexity is not constant

**Comment by jchia** [comment]
In some use cases, the user needs to use `tail`, so if it's not in foldl, he'll still just going to write it himself, anyway. Is it OK to add `tail` with documentation that the space complexity is not constant?

An example of a use case where the user needs to use `tail`: In the turtle package, `Shell Line` and folds are used a lot. If you don't want to use that paradigm, you can get extract from it a `[Line]` and do your own processing using list operations instead of folds. When a user needs to do the turtle equivalent of the bash line `some-command | tail -n +2 | sort | uniq`, because there is no `tail` fold, he could either write his own `tail` fold or switch from `Shell Line` processing to `[Line]` processing to handle the part for the `tail -n +2`.

Or, would you say `tail` is something for a downstream package like turtle to implement?

**Comment by Gabriel439** [comment]
@jchia: Note that there is a `drop` `Fold` that might do what you want:

https://hackage.haskell.org/package/foldl-1.4.9/docs/Control-Foldl.html#v:drop

**Comment by jchia** [comment]
Thanks, I didn't realize there was `drop`.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
