### ISSUE TITLE
Make Folds instances of Arrow?

### ISSUE THREAD

**Issue by turion** [Gabriel439/Haskell-Foldl-Library#160]
It seems like `Fold` and `FoldM` should be instances of `Category` and `Arrow`.

**Comment by turion** [comment]
They should then satisfy the law `scan fold1 >>> scan fold2 = scan (fold1 >>> fold2)`.

**Comment by Gabriel439** [comment]
@turion: Yeah, I was hoping that those types would be instances of `Category`, but as far as I know there isn't a law-abiding `Category` instance for `Fold`/`FoldM`

**Comment by turion** [comment]
Ah. I thought that something like this would work:

```
instance C.Category Fold where
  id = Fold const undefined id
  Fold step2 begin2 done2 . Fold step1 begin1 done1 = Fold step begin done
    where
      step (x1, x2) a = let x1' = step1 x1 a in (x1', step2 x2 $ done1 x1')
      begin = (begin1, begin2)
      done (_, x2) = done2 x2
```
But it crashes. It seems there is no way to implement `id` because we simply can't know the initial state. In other words, if we have both `Category` and `Comonad`, we can do `extract id :: a`, which can only crash or hang.

**Comment by MasseR** [comment]
As a theoretical idea, would this work:

1. Modify the `Fold` type to include a carrier for `a -> b`
2. Modify the `x -> b` to be `Fold x b`

Then you can compose on the extraction step

``` haskell
data Fold a b where
  Fun :: (a -> b) -> Fold a b
  Fold :: (x -> a -> x) -> x ->  (Fold x b) -> Fold a b

instance Category Fold where
  id = Fun id
  Fun f . Fun g = Fun (f . g)
  f . Fold g x extract = Fold g x (f . extract)
  Fold f x extract . Fun g = Fold (\x' a -> f x' (g a)) x extract
```
