### ISSUE TITLE
pretraverse's type is too strict

### ISSUE THREAD

**Issue by glguy** [Gabriel439/Haskell-Foldl-Library#32]
pretraverse currently requires a Traversal', but it doesn't need the full power of a Traversal', it would be happen with a mere Control.Lens.Fold.

This came up on #haskell where someone wanted to use pretraverse with a fold.

If it's type was

````haskell
pretraverse ::
  (forall x. (b -> Const (Endo x) b) -> a -> Const (Endo x) a) ->
  Fold b r -> Fold a r

-- or with lens type synonyms
pretraverse ::
  (forall x. Getting (Endo x) a b) ->
  Fold b r -> Fold a r
````

It would then be usable with Getters and Folds from lens package without any implementation change.

**Comment by Gabriel439** [comment]
So `pretraverse` was renamed to `handles` and it was fixed to use the the narrower type that only expects a `Fold`
