### ISSUE TITLE
Add revList

### ISSUE THREAD

**Issue by treeowl** [Gabriel439/Haskell-Foldl-Library#33]
Sometimes you want it backwards; sometimes you just want it fast.

```haskell
revList :: Fold a [a]
revList = Fold (flip (:)) [] id
```

**Comment by Gabriel439** [comment]
Is this actually faster than `fmap reverse list`?

**Comment by treeowl** [comment]
I imagine so. I think the right question is probably whether `list` is
faster than `fmap reverse revList`.

**Comment by Gabriel439** [comment]
Oops!  I forgot that since this is a left fold computing the reverse of the list is more efficient.  Yeah, then I'll accept this.  Could you write up a pull request?

**Comment by treeowl** [comment]
Sure. I'll have to wait till I'm at a proper computer tonight.

**Comment by Gabriel439** [comment]
I found some time to add this myself, so don't worry.
