### ISSUE TITLE
Fold looks a Profunctor

### ISSUE THREAD

**Issue by srijs** [Gabriel439/Haskell-Foldl-Library#36]
`Fold` looks like a profunctor:

    instance Profunctor Fold where
        lmap = premap
        rmap = fmap

Is there interest in declaring it as such?

**Comment by Gabriel439** [comment]
My original policy used to be to wait until `profunctors` was in the Haskell Platform, but now that the Haskell Platform is being deemphasized I'm okay with taking on the `profunctors` dependency.  Could you submit a pull request to add this?

**Comment by michaelt** [comment]
`profunctor` will add these dependencies

    nats
    stm
    StateVar
    tagged
    hashable
    transformers-compat
    distributive
    unordered-containers
    semigroups
    void
    contravariant
    comonad

Which suggests that a number of other instances should be written. Several are defined for the 'pure'  `Fold` type https://github.com/ekmett/folds/blob/master/src/Data/Fold/L'.hs

**Comment by Gabriel439** [comment]
My policy is to add instances on a "need-to-have" basis to avoid diluting the instance list with type classes that would distract from the important ones (i.e. `Applicative`).
