### ISSUE TITLE
[Question] How to fold a list of IO

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Foldl-Library#45]
I have some input of type `[IO (Maybe a)]`. I need to get the number of failure and the length of the array.

How can I possibly do that using an applicative fold ?

This is the real code and I was wondering if it was possible to do something more clever (more efficient) with foldl:

```
countFailure :: [Maybe a] -> Int
countFailure = length . filter isNothing

-- | For each node, queryfunc the catalog and return stats
computeStats :: QueryFunc -> [Nodename] -> IO ()
computeStats queryfunc nx = do
  failures <- countFailure <$> parallel (map (computeCatalog queryfunc) nx)
  let nbnodes = length nx
  putStr ("Tested " ++ show nbnodes ++ " nx. ")

  if failures > 0
    then do {putDoc ("Found" <+> red (int failures) <+> "failure(s)." <> line) ; exitFailure}
    else do {putDoc (dullgreen "All green."  <> line) ; exitSuccess}

  where
    computeCatalog :: QueryFunc -> Nodename -> IO (Maybe (FinalCatalog, EdgeMap, FinalCatalog, [Resource]))
    computeCatalog func node = func node >>= S.either
                                 (\err -> putDoc ("Problem with" <+> ttext node <+> ":" <+> getError err </> mempty) >> return Nothing)
                                 (return . Just)
```

Thanks for your help. I hope you don't mind me crying for help through the list of issues ;-)

**Comment by Gabriel439** [comment]
I would write a function of type:

```haskell
parallel :: [IO b] -> Producer b IO ()
```

That would go through the input list of `IO` actions, launch many of them in parallel, and then have the `Producer` emit the results in whatever order they come back.  Then for the special case where `b = Maybe a` you could count how many successes there were by writing:

```haskell
input :: [IO (Maybe a)]

parallel input :: Producer (Maybe a) IO ()

parallel input >-> Pipes.Prelude.concat :: Producer a IO ()

Pipes.Prelude.length (parallel input >-> Pipes.Prelude.concat) :: IO Int
```

So that just leaves the implementation of the `parallel` function, which you can do with `pipes-concurrency`.

**Comment by PierreR** [comment]
@Gabriel439 Thanks for your help.

I would go with
```
countFailure :: L.Fold (Maybe a) Int
countFailure = L.Fold step 0 id
  where
    step :: Int -> Maybe a -> Int
    step x = maybe (x+1) (const x)

computeStats queryfunc nx = do
  mx <- mapConcurrently (computeCatalog queryfunc) nx
  let (nbnodes, failures) = L.fold ((,) <$> L.length <*> countFailure) mx
```
Actually it makes me realize there is little gain unless the list is very very big.

**Comment by PierreR** [comment]
A little question. Is `foldl` always meant to provide **sequential** streaming left folds ?

**Comment by Gabriel439** [comment]
There is no way to process elements in parallel, if that is what you are asking

**Comment by PierreR** [comment]
Yes, thanks. That's what just for confirmation ;-) 

AFAIK, the word  `streaming` doesn't convey that fact so it might be a plus to be more explicit in the description of the package (l guess it might not be that obvious for people that are less familiar with Haskel).
