### ISSUE TITLE
More stock `FoldM`s?

### ISSUE THREAD

**Issue by michaelt** [Gabriel439/Haskell-Foldl-Library#46]
Is there are reason why FoldMs more or less like these

    toHandle :: IO.Handle -> FoldM IO String ()  -- for string this should maybe (also) be toHandleLn?
    toHandle h = FoldM step begin done where
      done  = return 
      begin = return ()
      step () str = IO.hPutStr h str

    stdout ::  FoldM IO String () -- for string, this should perhaps be stdoutLn
    stdout = FoldM step begin done where
      done  = return 
      begin = return ()
      step () str = IO.putStr str 

    stderr :: FoldM IO String ()
    stderr = FoldM step begin done where
      done  = return 
      begin = return ()
      step () str = IO.hPutStrLn IO.stderr str -- here putStrLn seems very natural

are unsafe or unreasonable?

I was wanting to use bytestring equivalents for a still somewhat imaginary tutorial for these streaming and streaming-bytestring libraries I pieced together. (`Foldr` and `FoldM` are the natural consumer/sink types for these discount producer types, I wanted to say.) 

Examples like

     L.handlesM _Left stderr <> L.handlesM _Right (L.premapM show (toHandle h))

are extremely attractive, and would make a nice demo in the haddocks for `foldl`

**Comment by Gabriel439** [comment]
I would prefer to provide a single function to unify all three patterns (similar to the one in `mvc`):

```haskell
sink :: (Monoid r, Monad m) => (a -> m r) -> FoldM a m r
```

... that would obey these laws (if the `Monoid` was commutative):

```haskell
sink (f <> g) = sink f <> sink g

sink mempty = mempty
```

**Comment by michaelt** [comment]
I wondered why `sink` was missing too.

     L.handlesM _Left (sink $ IO.hPutStrLn IO.stderr) <> L.handlesM _Right (sink print)

is a little verbose but intelligible, `sink print` is on reflection pretty good.

Should sink be written directly 

     sink ::  (Monoid w, Monad m) => (a -> m w) -> FoldM m a w
     sink act = FoldM step begin done  where
       done = return
       begin = return mempty
       step m a = do
         m' <- act a
         return $! m <> m'

or should it accumulate `(w -> m w)` , so `done k = k mempty` ?

**Comment by Gabriel439** [comment]
I think the former implementation will run in constant space whereas the latter one would not.

**Comment by michaelt** [comment]
No, I gave up on it immediately trying out in ghci ... I was thinking of the functions that consume Folds.

**Comment by michaelt** [comment]
I was composing a patch, but is this bit of haddock too laborious. (I could also refer to `mvc`)


    {-| @sink action@ returns a 'FoldM' which applies the action at each step,
        accumulating a monoidal value. If the monoid @w@ is commutative and the monad
        supports the standard monoid instance for @m w@, then 

    > sink (f <> g) = sink f <> sink g
    > sink mempty = mempty


    >>> L.foldM (L.sink print) [10..12]
    10
    11
    12

    >>> let logFold h = L.handlesM _Right (L.sink print) <> L.handlesM _Left (L.sink (IO.hPutStrLn h))
    >>> let parses = [Left "Bad parse", Right 23, Left "Ran out of bytes", Right 22]
    >>> IO.withFile "log" IO.AppendMode $ \h -> L.foldM (logFold h) parses
    23
    22
    >>> :! cat log
    Bad parse
    Ran out of bytes
    -}


    sink ::  (Monoid w, Monad m) => (a -> m w) -> FoldM m a w
    sink act = FoldM step begin done  where
      done = return
      begin = return mempty
      step m a = do
        m' <- act a
        return $! mappend m m'

**Comment by Gabriel439** [comment]
Maybe simplify it to:

```haskell
{-| Converts an effectful function to a fold

> sink (f <> g) = sink f <> sink g -- if `(<>)` is commutative
> sink mempty = mempty
-}
```

**Comment by michaelt** [comment]
Yes, that seems as well, just a sec.
