### ISSUE TITLE
Add variant of `purely` for normal `foldl`s

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Foldl-Library#48]
Some libraries (e.g. `bytestring`) provide a function analogous to list `foldl`. I wrote an adapter `wrap g f i o = g . f i o` so that I can write `purely (wrap foldl)`, but the types for `purely' f = purely (wrap f)` don't work out.

I think this would be a useful adapter function to have in the library, so that even code released without knowledge of `foldl` could be used easily in conjunction with it.

**Comment by Gabriel439** [comment]
Yes, I agree.  Maybe we could name these variants `purely_` and `impurely_` unless you had any naming preferences of your own

**Comment by rpglover64** [comment]
Seems reasonable.
