### ISSUE TITLE
allow 'map' and 'zip' before fold

### ISSUE THREAD

**Issue by amigalemming** [Gabriel439/Haskell-Foldl-Library#5]
I like to have a way to do 'map's and 'zip's before the fold. That is, there should be a function L.compose satisfying

  L.fold (L.compose f g) xs  =  L.fold f $ fmap g xs

and a function L.feed with

  L.fold (L.feed f gen) xs  =  L.fold f $ zip (L.unfold gen) xs

'gen' should be a stream producer, in contrast to the fold 'f', which is a stream consumer. 'L.unfold gen' should generate the according list, like List.unfoldr does.

Those extensions would be great, since we could use 'map' and 'zip' on types like 'StorableVector', where certain element types are not allowed (e.g. functions). That is, we could use 'map' and 'zip' in combination with a fold, where we could not use them alone.

**Comment by Gabriel439** [comment]
This is a very very long-delayed solution, but now you can directly `zip` two folds using `handles` and the `_1`/`_2` lenses from `lens-family-core`:

```haskell
import Control.Foldl (handles)
import Lens.Family.Stock (_1, _2)

fold1 :: Fold a b
fold2 :: Fold c d

zip :: Fold a b -> Fold c d -> Fold (a, c) (b, d)
zip fold1 fold2 = (,) <$> handles _1 fold1 <*> handles _2 fold2
```

This generalizes to an arbitrary tuple size (assuming you use the more general tuple lenses from `Control.Lens`).  For example, if you wanted to zip three folds, you would write:

```haskell
import Control.Lens (_1, _2, _3)

zip fold1 fold2 fold3 = (,,) <$> handles _1 fold1 <*> handles _2 fold2 <*> handles _3 fold3
```

Would that solution work for you?

**Comment by Gabriel439** [comment]
I will mark this closed for now unless there are any other questions
