### ISSUE TITLE
MonadIO, hoisting etc.

### ISSUE THREAD

**Issue by michaelt** [Gabriel439/Haskell-Foldl-Library#51]
I was defeated trying to apply `randomN` inside a `MonadResource`/`MonadSafe` sort of constraint - basically "get a vector of n random words from /usr/share/dict/words" .  If the parameters for `FoldM` were rearranged, I guess it would have a valid `MFunctor` instance since the monadic elements are always in positive position.  But is there place for something like `hoist` or, for the special case of `MonadIO`

    liftingIO (L.FoldM step begin done) = L.FoldM (\a b -> liftIO (step a b)) (liftIO begin) (\x -> liftIO (done x))

I feel like I'm missing some obvious way to do this that is already  present in the library.

**Comment by Gabriel439** [comment]
I could definitely add a `hoist` specialized to `FoldM`.  I agree that the type parameter order is problematic since you can't implement both `Profunctor` and `MFunctor`.

**Comment by michaelt** [comment]
Certainly it seems better to have such an expression around than to labor to make all FoldM's general across MonadIO. I'm as usual devoid of inspiration thinking what it might be called, I can only think of things that allude to `lift` and `hoist` like `liftWith` or `hoisting` at the moment. It is a fairly unpretentious combinator, less like `lift` and `hoist` more like `generalize`

**Comment by Gabriel439** [comment]
How about `hoists`?  If that name is alright with you then I can add it

**Comment by michaelt** [comment]
That sounds great.

**Comment by michaelt** [comment]
Just a minute, if you haven't written it, I will send a patch; you'll have to figure out the documentary comment ...

**Comment by michaelt** [comment]
So here's a patch if you haven't written one https://github.com/Gabriel439/Haskell-Foldl-Library/pull/52

**Comment by Gabriel439** [comment]
Thanks!  I appreciate it :)
