### ISSUE TITLE
Foldl documentation not showing up properly on Hackage

### ISSUE THREAD

**Issue by sid-kap** [Gabriel439/Haskell-Foldl-Library#55]
For some reason, at https://hackage.haskell.org/package/foldl, under "Modules", the links to "Control.Foldl", "Control.Foldl.ByteString", and "Control.Foldl.Text" aren't clickable. 

Thankfully, it is still working at Stackage (https://www.stackage.org/package/foldl).

Is this issue likely to be from the project, or from the Hackage maintainers' end?

**Comment by Gabriel439** [comment]
Thanks for pointing this out!  I fixed it
