### ISSUE TITLE
Post-map for FoldM?

### ISSUE THREAD

**Issue by sid-kap** [Gabriel439/Haskell-Foldl-Library#56]
I noticed that `Fold` has a `Functor` instance, so that we can "post-map" the result of our fold using `fmap`:
```haskell
postMap :: (b -> c) -> Fold a b -> Fold a c
postMap = fmap
```
Is there a monadic analogue of this for `FoldM`, like the following
```haskell
postMapM :: (b -> m c) -> FoldM m a b -> FoldM m a c
```
?

I apologize if I missed something by not reading the docs carefully. I looked at `handles` and `handlesM`, but, as I understand it, those functions are for transforming the input before the actual fold, not after.

**Comment by Gabriel439** [comment]
Yeah, it's not in there, but it's pretty easy to write.  If you want you can contribute it!

The laws for this would be pretty straightforward:

```haskell
postMapM return = id
postMapM (g <=< f) = postMapM g . postMapM f
```

**Comment by sid-kap** [comment]
Sorry for leaving this open for so long! I ended up not needing this, so I didn't send the PR. I'll close this for now.
