### ISSUE TITLE
Implement fold/foldM for MonoFoldable class?

### ISSUE THREAD

**Issue by TerrorJack** [Gabriel439/Haskell-Foldl-Library#60]
I wonder if introducing `mono-traversable` dependency and implement `fold`/`foldM` for `MonoFoldable` is a good idea. If so, I can open a pull request for this.

**Comment by michaelt** [comment]
TerrorJack, I'm not sure Gabriel knows of it, but this is provided for inside `Data.MonoTraversable` using the `Unwrap` suffix.  

      >>> import Data.MonoTraversable
      >>> import Data.Text
      >>> import qualified Control.Foldl as L
      >>> L.purely ofoldlUnwrap ((,) <$> L.length <*> L.last) ("hello" :: Text)
     (5,Just 'o')
     >>> import qualified Data.Vector.Unboxed as U
     >>>  L.impurely ofoldMUnwrap (L.randomN 3) ("california" :: Text)   :: IO (Maybe (U.Vector Char))
    Just "cir"

It might be nice to help forming the mental abstraction needed for `purely` and `impurely` if the documentation, after [the discussion of  `L.purely Pipes.fold` and `L.impurely Pipes.foldM`](https://github.com/Gabriel439/Haskell-Foldl-Library/blob/master/src/Control/Foldl.hs#L800) also gave example for `purely ofoldlUnwrap` and `impurely ofoldMUnwrap` as examples somehow.

**Comment by Gabriel439** [comment]
I would be happy to add documentation examples of how to use `purely` and `impurely` with `monotraversable`.

**Comment by michaelt** [comment]
So I guess it could continue something like this, or maybe just use an example 

        The 'ofoldlUnwrap' and 'ofoldMUnwrap' in 'Data.MonoTraversable' 
       are similarly designed for use with a 'Fold' or 'FoldM':

    >  L.purely ofoldlUnwrap
    >    :: MonoFoldable mono => L.Fold (Element mono) b -> mono -> b

    >  L.impurely ofoldMUnwrap
    >    :: (Monad m, MonoFoldable mono) =>
    >       L.FoldM m (Element mono) b -> mono -> m b
