### ISSUE TITLE
`Fold` vs `FoldM Identity`

### ISSUE THREAD

**Issue by tswilkinson** [Gabriel439/Haskell-Foldl-Library#63]
This isn't really an issue, I'm just curious: why not have `type Fold a b = FoldM Identity a b`?  Is there any real difference between the two?

Having `type Fold a b = FoldM Identity a b` and `type Handler a b = HandlerM Identity a b` would mean that `generalize`, `simplify`, `premapM`, and `handlesM` could disappear.  However, I think `Comonad (FoldM Identity a)` would require `FlexibleInstances` or something.

**Comment by Gabriel439** [comment]
It's mainly to simplify inferred types and error messages for the `Fold` type.  The last time I measured performance there was no performance penalty for implementing `Fold` in terms of `FoldM`.

Given that `Fold` is the overwhelmingly common use case I'm okay with incurring explicit conversions between the two types just to improve the user experience on the happy path.

**Comment by tswilkinson** [comment]
OK, it's up to you.  If only we had slightly more customizable error messages, that wouldn't be a problem...
