### ISSUE TITLE
Fold vs FoldM

### ISSUE THREAD

**Issue by michaelt** [Gabriel439/Haskell-Foldl-Library#70]
In the little flurry of benchmarking a couple weeks ago I came across some old material that had come up in [issue 10](https://github.com/Gabriel439/Haskell-Foldl-Library/issues/10) and maybe earlier, about the possibility of assimilating `Fold` and `FoldM`.  Trapped in an airport, I reworked and updated the old implementation to be a dependent module [`Control.FoldM`](https://github.com/michaelt/foldm/blob/master/src/Control/FoldM.hs) exporting the same API as `Control.Foldl` but ignoring the existence of `Fold`, so to speak. https://github.com/michaelt/foldm 

I added benchmarks for a bunch of stock folds. They seem to show that, at least in the somewhat weird world criterion creates, pure folds have no advantage. You can see the results here fwiw http://michaelt.github.io/bench/stock_folds.html 
In each quartet, the first benchmark is of the direct fold over the appropriate type, e.g. Foldable.sum, Vector.Unboxed.sum, etc. (marked `prelude`); the second applies the associated `Control.Foldl.Fold` (marked `pure`); the third and fourth apply a `Control.Foldl.FoldM`. Notice that the impure folds are frequently faster, though I expect this is just curiosities about inlining and so on in the presence of `whnf`.  The labor of implementing the folds directly (these are the ones marked `impure`) rather than just applying `generalize` seems to have been basically pointless (the earlier source was supposed to be a monadic replacement for `Fold`). This proves the merits of `generalize`, not that anyone was doubting them. There is also an ancillary benchmark of folds composed with the applicative instance http://michaelt.github.io/bench/compose_folds.html which had been causing me trouble earlier. 

It seems to me that, at least where one is using effectful sequences like Pipes `import Control.FoldM` might be conceptually simpler anyway, since e.g. the transition from say

     >>> M.impurely P.foldM M.sum $ each [1..5]
     15

to 

     >>> M.impurely P.foldM (M.sum <* M.sink print) $ each [1..5]
     1
     2
     3
     4
     5
     15

is so much simpler. 

Anyway, I thought these benchmarks might interest you.

**Comment by Gabriel439** [comment]
Yeah, my own benchmarks that I've done in the past confirmed that there is no performance advantage of `Fold` over `FoldM Identity`.  However, I'd still like to keep the `Fold` type separate for better inferred types and better error messages.

**Comment by michaelt** [comment]
Yes, of course; the `Fold` type is in any case much more intelligible as the reified arguments to a `foldl'`, and so is necessary.  I was wondering, though, if it  seemed like a reasonable separate helper package. ---The idea being that it streamlines thinking when you are going to use one of more `FoldM` anyway.  Where the sequence you are folding over is itself effectful, this is pretty common. `FoldM`s can be advertised as a restricted but (thereby) ultra-composable variant of the sort of sink or consumer we find in the streaming io libraries ... and so on.  I will think about it more.

**Comment by Gabriel439** [comment]
The main difficulty is that you would have to copy all the `Fold`s to generalize them to `FoldM`, which would duplicate a lot of code

**Comment by michaelt** [comment]
Yes, it would emphatically be duplication! One reason to object to this is that it doesn't centralize errors and thus tends to multiply them. But part of the purpose of the exercise above was to show that `generalize` basically has no cost, so if I were going to package a helper `Control.FoldM` module I think it would thus use `generalize` on principle for the 10 or 15 pure stock folds, `sum` , `length` `elem` etc. that are mostly under discussion. (The duplication needed for the class instances is inside `Control.Foldl` already.)  This is transparently a triviality, and would be explained as such in the documentation. But by re-exporting the rest of the `FoldM` material from `Control.Foldl` one would achieve a unification aimed at a restricted range of purposes that don't obsolete `Fold` by any means. The user will have to understand the `Fold`/`FoldM` relation anyway, and the `Fold` type is simpler. The matter takes on a different complexion once one sees that `FoldM` is a partial replacement for the `Sink/Consumer/OutputStream` concepts from the streaming io libraries; and that by restricting their power in some ways, `FoldM`s win the advantage that they are composable or superimposable by the Applicative instance and targetable via `handlesM`; and so on. All this is in `Control.Foldl` of course. But my half-baked thought is it isn't sufficiently obvious; `FoldM` seems like a super-fancy `Fold`, rather than a super-simple, super-composable `Sink` / `Consumer` / etc. Anyway, it's just an idea. I hadn't realized you had benched `FoldM`s, which cancels much of the purpose of this issue, or whatever it is...

**Comment by PierreR** [comment]
Sorry if this is only slightly related but I would be interested in understanding `Pipes` from `FoldM`. Is this possible ? I mean `Fold` is easy to grok, `FoldM` would follow naturally and if there were a kind of bridge to go from there to `Pipes` ...

**Comment by michaelt** [comment]
It is only the end of a pipeline, the Pipes `Consumer` or Conduit `Sink`, that is similar to a `Fold` or `FoldM` and can frequently be replaced by one.  So it's just a very special case of a pipe that can be re-analysed in terms of `foldl`.  Thus, to take a trivial example, given a file with numbers on each line, instead of writing

     runEffect $ P.fromHandle h >-> P.map read >-> P.print  -- or whatever

you can equally write

     L.impurely P.foldM (L.sink print) $  P.fromHandle h >-> P.map read

Written that way, you can immediately throw in other folds, e.g.

     L.impurely P.foldM (L.generalize L.sum <* L.sink print) $ P.fromHandle h >-> P.map read

or supposing you sensible enough to use `readMaybe`, you might have written 

     L.impurely P.foldM (L.handlesM _Just (L.generalize L.sum <* L.sink print)) $ P.fromHandle h >-> P.map readMaybe

to catch only the good parses. But then, you could keep a count of bad parses, say, by adding `L.handlesM _Nothing L.length` and so on. 

For various reasons, `pipes` in fact prefers not to write folds that actually collect information as `Consumers`. Things like `P.sum` or `P.toListM`, are written as functions acting directly on a producer. The producer  may of course be written with a pipeline:

      P.sum $ P.fromHandle h >-> P.map readMaybe >-> P.concat 

which is 

    L.purely P.fold L.sum $ P.fromHandle h >-> P.map readMaybe >-> P.concat 

But in conduit, as it stands, things like `sum` and `toListM`, written as `fold (+) 0` and `sinkList`, are written as `Sink`s ; the user is never permitted to apply a function directly to a conduit `Source`. 

Anyway, in the above, I was imagining a sort of helper module `Control.FoldM` that might give one occasion to bring these things out by thematizing 'fold as sink' and standardizing, for that purpose on `FoldM`. But Gabriel is presumably right that it would be more trouble than it is worth.

**Comment by PierreR** [comment]
Thanks for all this little thoughts and notes.

Given that monad is about unfolding and comonad about folding, there is technically a way to construct `pipes` or such streaming abstraction using free (producer) and cofree (consumer, folding) only ? Is that more or less correct ?

**Comment by Gabriel439** [comment]
The closest thing to `pipes` in terms of `FoldM` is my `turtle` library, where `FoldM` plays the role of a `Consumer` and `Shell` plays the role of a `Producer`, and `fold` is how you connect them together.

**Comment by michaelt** [comment]
Right, I guess I would have said that `turtle` is distinctive in explaining the idea of a stream / producer as 'thing that can be fed systematically and without remainder to a monadic left fold`; it thus enforces the rule that all consumption of a stream/shell is by a monadic left fold. But of course any form of stream/producer/source can be consumed by a monadic left fold, even if it is explained in such a way that other things can be done with it.
