### ISSUE TITLE
Should there be an `id` Fold?

### ISSUE THREAD

**Issue by fhaust** [Gabriel439/Haskell-Foldl-Library#84]
Say I want "the current item and the last item" in a list, I'd need an `id` Fold, do I?

    thisAndLast = (,) <$> F.id <*> F.previous

(obviously more useful on scans)

Or is that hidden in a typeclass somewhere?

Where `id` is probably:

    id :: F.Fold a a
    id = F.Fold (\_ x -> x) undefined id

But this actually evaluates `undefined` when used with `F.scan` and crashes.

**Comment by michaelt** [comment]
Note, for what it's worth that you can get something like the particular effect you seem to want above with `lastN`

    >>> mapM_ print $ L.scan (L.lastN 2) [1..5]
    []
    [1]
    [1,2]
    [2,3]
    [3,4]
    [4,5]

    >>> let b = fmap listToMaybe  (L.lastN 2)
    >>> mapM_ print $ L.scan (liftA2 (,) b L.last) [1..5]
    (Nothing,Nothing)
    (Just 1,Just 1)
    (Just 1,Just 2)
    (Just 2,Just 3)
    (Just 3,Just 4)
    (Just 4,Just 5)

**Comment by fhaust** [comment]
Hmm ... so `id` is basically `last` in the context of scan. Didn't consider that.
