### ISSUE TITLE
Use "vector-builder"

### ISSUE THREAD

**Issue by nikita-volkov** [Gabriel439/Haskell-Foldl-Library#88]
According to [the benchmark](https://github.com/nikita-volkov/vector-builder/blob/b621b2033c7605b12c029b3bde08b41e0b3f8155/foldl-benchmark/Main.hs), it's several times faster than the current implementation and it doesn't require the `FoldM` abstraction, `Fold` is enough.

Following are the benchmark results:

```
benchmarking vector-builder
time                 82.43 μs   (82.16 μs .. 82.84 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 82.79 μs   (82.41 μs .. 83.38 μs)
std dev              1.579 μs   (1.104 μs .. 2.078 μs)
variance introduced by outliers: 14% (moderately inflated)

benchmarking default
time                 217.1 μs   (211.7 μs .. 223.8 μs)
                     0.994 R²   (0.990 R² .. 0.998 R²)
mean                 212.8 μs   (210.2 μs .. 216.8 μs)
std dev              10.99 μs   (6.764 μs .. 16.42 μs)
variance introduced by outliers: 50% (moderately inflated)
```

**Comment by Gabriel439** [comment]
Take a look at https://github.com/Gabriel439/Haskell-Foldl-Library/pull/89 and let me know if that is what you had in mind
